# Generated by Django 6.1 on 2026-08-17 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('letter_type', models.CharField(blank=True, max_length=120)),
                ('student_id', models.CharField(blank=True, max_length=40)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('contractor', models.CharField(blank=True, max_length=200)),
                ('contractor_position', models.CharField(blank=True, max_length=200)),
                ('internship_position', models.CharField(blank=True, max_length=200)),
                ('period', models.CharField(blank=True, max_length=120)),
                ('data', models.JSONField()),
            ],
            options={
                'ordering': ['row_index'],
            },
        ),
        migrations.CreateModel(
            name='UploadedBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('skipped', 'Skipped')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='generated_letters/')),
                ('skip_reason', models.CharField(blank=True, max_length=255)),
                ('ref_no', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='letters.studentrecord')),
            ],
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='letters.uploadedbatch'),
        ),
        migrations.CreateModel(
            name='GenerationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documents', models.ManyToManyField(related_name='generation_batches', to='letters.generateddocument')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='letters.uploadedbatch')),
            ],
        ),
    ]
