# Generated by Django 5.1.14 on 2026-08-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generateddocument",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="signed_file",
            field=models.FileField(blank=True, null=True, upload_to="signed_docs/"),
        ),
    ]
