# Generated by Django 5.1.14 on 2026-09-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0004_uploadedbatch_uploaded_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentrecord",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="course_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="semester",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="times",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="company",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="contractor",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="contractor_position",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="display_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="internship_position",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="letter_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="period",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="row_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="student_id",
            field=models.CharField(max_length=50),
        ),
    ]
