# Generated by Django 5.1.14 on 2026-09-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "letters",
            "0005_alter_studentrecord_options_studentrecord_course_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "letter_type",
                    models.CharField(
                        choices=[
                            ("request", "Internship Request Letter"),
                            ("confirm", "Internship Confirmation Letter"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("file", models.FileField(upload_to="letter_templates/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("UPLOAD_EXCEL", "Uploaded Excel Batch"),
                    ("GENERATE_DOCS", "Generated Draft Letters"),
                    ("UPLOAD_SIGNED", "Uploaded Signed PDFs"),
                    ("SEND_EMAIL", "Dispatched Emails"),
                    ("EDIT_RECORD", "Edited Student Record"),
                    ("ADD_RECORD", "Manually Added Student Record"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="generateddocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("generated", "Generated"),
                    ("skipped", "Skipped"),
                    ("sent", "Sent"),
                ],
                max_length=20,
            ),
        ),
    ]
