# Generated by Django 5.1.14 on 2026-09-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0006_lettertemplate_alter_auditlog_action_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=20)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("letter_type", models.CharField(max_length=50)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("course_id", models.CharField(blank=True, max_length=100, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "signed_file",
                    models.FileField(
                        blank=True, null=True, upload_to="signed_letters/"
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="lettertemplate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="lettertemplate",
            name="letter_type",
            field=models.CharField(
                choices=[
                    ("request", "Internship Request Letter"),
                    ("confirm", "Internship Confirmation/Referral Letter"),
                    ("extension", "Internship Extension Letter"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
