# Generated by Django 5.1.14 on 2026-09-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0007_studentletter_lettertemplate_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrecord",
            name="year",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
