# Generated by Django 5.1.14 on 2026-09-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0008_studentrecord_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateFieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placeholder", models.CharField(max_length=100)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("field", "Data Field"),
                            ("static", "Static Text"),
                            ("unmapped", "Not Mapped Yet"),
                        ],
                        default="unmapped",
                        max_length=10,
                    ),
                ),
                (
                    "source_value",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="letters.lettertemplate",
                    ),
                ),
            ],
            options={
                "unique_together": {("template", "placeholder")},
            },
        ),
    ]
