# Generated by Django 5.1.14 on 2026-09-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0009_templatefieldmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="LetterTypeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_text", models.CharField(max_length=255, unique=True)),
                (
                    "letter_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="letters.lettertype",
                    ),
                ),
            ],
        ),
    ]
