# Generated by Django 5.1.14 on 2026-09-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letters", "0010_lettertype_lettertypemapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("total_records", models.IntegerField(default=0)),
            ],
        ),
    ]
